version: '3'

services:
    nodejs:
        container_name: weather-app
        build:
            context: .
            dockerfile: Dockerfile
        command: nodemon --inspect app.js
        # env_file:
        #   - "./.env"
        ports:
            - '8888:8080'
        volumes:
            - '.:/usr/src/app'
            - '/usr/src/app/node_modules'
        networks:
            - localnet
volumes:
    node_modules:
    web-root:
        driver: local
networks:
    localnet:
        driver: 'bridge'
